name: 'xccov2lcov'
description: 'Convert xccov and xcresult data to lcov'
author: 'Lukas Kollmer <contact@lukaskollmer.de>'
branding:
  icon: 'terminal'
  color: 'blue'
inputs:
  xcresult:
    description: 'xcresult bundle'
    required: true
    type: string
#  targets:
#    description: 'which targets should be included'
#    required: false
#    type: 
runs:
  using: "composite"
  steps:
    - name: Build xccov
      shell: bash
      run: swift build -c release --product xccov2lcov
      working-directory: ${{ github.action_path }}
    - name: xccov
      shell: bash
      run: xcrun xccov view --report --json ${{ inputs.xcresult }} | ${{ github.action_path }}/.build/release/xccov2lcov > info.lcov
