#
# This source file is part of the Stanford Biodesign for Digital Health open-source project
#
# SPDX-FileCopyrightText: 2025 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: 'xccov2lcov'
description: 'Convert xccov and xcresult data to lcov'
author: 'Lukas Kollmer <contact@lukaskollmer.de>'
branding:
  icon: 'terminal'
  color: 'blue'
inputs:
  xcresult:
    description: 'xcresult bundle'
    required: true
runs:
  using: "composite"
  steps:
    - name: Download xccov2lcov
      shell: bash
      run: |
        set -e
        # Download the latest precompiled binary
        wget https://github.com/StanfordBDHG/xccov2lcov/releases/latest/download/xccov2lcov-macos.tar.gz
        # Extract and make executable
        tar -xzf xccov2lcov.tar.gz
        chmod +x xccov2lcov
        # Add the binary's location to the PATH for subsequent steps
        echo "${{ github.action_path }}" >> $GITHUB_PATH
    - name: Run xccov2lcov
      shell: bash
      run: |
        xcrun xccov view --report --json ${{ inputs.xcresult }} | xccov2lcov > info.lcov
